name: "Test & Build"
on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: run tests
        run: bash ./gradlew test

  apk:
    name: Build APks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: build
        run: bash ./gradlew app:assembleRelease tv:assembleRelease
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: app & tv
          path: ./**/build/outputs/apk/release/*.apk
