name: "Test & Build"
on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      API_KEY_TMDB: ${{ secrets.API_KEY_TMDB }}
      API_KEY_TRAKT: ${{ secrets.API_KEY_TRAKT }}

    steps:
      - uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
          echo "API_KEY_TMDB=${API_KEY_TMDB}" >> ./gradle.properties
          echo "API_KEY_TRAKT=${API_KEY_TRAKT}" >> ./gradle.properties

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/wrapper/*
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: run tests
        run: bash ./gradlew test detekt

  apk:
    name: Build APKs
    runs-on: ubuntu-latest
    env:
      API_KEY_TMDB: ${{ secrets.API_KEY_TMDB }}
      API_KEY_TRAKT: ${{ secrets.API_KEY_TRAKT }}

    steps:
      - uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
          echo "API_KEY_TMDB=${API_KEY_TMDB}" >> ./gradle.properties
          echo "API_KEY_TRAKT=${API_KEY_TRAKT}" >> ./gradle.properties

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/wrapper/*
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: build
        run: bash ./gradlew app:assembleRelease tv:assembleRelease
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: app & tv
          path: ./**/build/outputs/apk/release/*.apk
