name: "Validate Gradle Wrapper"
on: [ pull_request ]

jobs:
  validation:
    name: "Validation"
    runs-on: buildjet-16vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
